### ISSUE TITLE
Trouble getting it to run

### ISSUE THREAD

**Issue by JomSpoons** [Nisto/ps2-bankmod#1]
Hi, sorry if this is a stupid question but I've been having trouble trying to use this tool. Whenever I try and enter anything (in this case `e`) into the prompt, it just closes with an error. Here's the log from the command prompt.

```
Microsoft Windows [Version 10.0.17763.475]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Jom\Desktop\ps2-bankmod-master>ps2-bankmod.py
Enter 'e' to extract, 'i' to import: e
Traceback (most recent call last):
  File "C:\Users\Jom\Desktop\ps2-bankmod-master\ps2-bankmod.py", line 77, in <module>
    mode = get_lit_arg(['e','i'], "Enter 'e' to extract, 'i' to import: ")
  File "C:\Users\Jom\Desktop\ps2-bankmod-master\ps2-bankmod.py", line 72, in get_lit_arg
    x = input(message)
  File "<string>", line 1, in <module>
NameError: name 'e' is not defined
```

Again, I apologize if I'm just overlooking something but I just couldn't figure out the issue. Thank you very much.

**Comment by Nisto** [comment]
@JomSpoons Sorry for a late reply here. GitHub is notorious for having a poor notification system. I am currently in the process of closing the loop with old issues.

It looks like you are doing things correctly, and I just tested the script myself on Windows 10.0.19042.631 without any issues doing the same steps as you. So I'm really not sure what the issue could be. But I would suggest updating Python if you haven't done so yet, or try using a different terminal. The issue may be related to your locale, encoding, character set or other language-related settings. In my case, `chcp` in `cmd` returns 437 and I am on a US/English locale with Swedish region/keyboard-layout. If that advice/information shouldn't help you solve things, give me another poke. For now I am closing this issue.
